// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.2
// source: nlp.proto

package nlp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_nlp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intent        string                 `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	TimeIso       string                 `protobuf:"bytes,2,opt,name=time_iso,json=timeIso,proto3" json:"time_iso,omitempty"`
	Task          string                 `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_nlp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractResponse) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *ExtractResponse) GetTimeIso() string {
	if x != nil {
		return x.TimeIso
	}
	return ""
}

func (x *ExtractResponse) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

var File_nlp_proto protoreflect.FileDescriptor

const file_nlp_proto_rawDesc = "" +
	"\n" +
	"\tnlp.proto\x12\x03nlp\"$\n" +
	"\x0eExtractRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"X\n" +
	"\x0fExtractResponse\x12\x16\n" +
	"\x06intent\x18\x01 \x01(\tR\x06intent\x12\x19\n" +
	"\btime_iso\x18\x02 \x01(\tR\atimeIso\x12\x12\n" +
	"\x04task\x18\x03 \x01(\tR\x04task2B\n" +
	"\n" +
	"NLPService\x124\n" +
	"\aExtract\x12\x13.nlp.ExtractRequest\x1a\x14.nlp.ExtractResponseB\fZ\n" +
	"/proto/nlpb\x06proto3"

var (
	file_nlp_proto_rawDescOnce sync.Once
	file_nlp_proto_rawDescData []byte
)

func file_nlp_proto_rawDescGZIP() []byte {
	file_nlp_proto_rawDescOnce.Do(func() {
		file_nlp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nlp_proto_rawDesc), len(file_nlp_proto_rawDesc)))
	})
	return file_nlp_proto_rawDescData
}

var file_nlp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nlp_proto_goTypes = []any{
	(*ExtractRequest)(nil),  // 0: nlp.ExtractRequest
	(*ExtractResponse)(nil), // 1: nlp.ExtractResponse
}
var file_nlp_proto_depIdxs = []int32{
	0, // 0: nlp.NLPService.Extract:input_type -> nlp.ExtractRequest
	1, // 1: nlp.NLPService.Extract:output_type -> nlp.ExtractResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nlp_proto_init() }
func file_nlp_proto_init() {
	if File_nlp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nlp_proto_rawDesc), len(file_nlp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nlp_proto_goTypes,
		DependencyIndexes: file_nlp_proto_depIdxs,
		MessageInfos:      file_nlp_proto_msgTypes,
	}.Build()
	File_nlp_proto = out.File
	file_nlp_proto_goTypes = nil
	file_nlp_proto_depIdxs = nil
}
